# Site settings
title: Coding School - Hackers Lab
email: nzhackerslab@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hackerslab.co.nz" # the base hostname & protocol for your site

twitter_username:
github_username: nzhackslab

# Build settings
markdown: kramdown
